/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106612-gea84eb2db1-20220414"
#endif /* AVUTIL_FFVERSION_H */
