/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106624-g391ce570c8-20220415"
#endif /* AVUTIL_FFVERSION_H */
